# Generated by Django 5.2.3 on 2025-06-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maskgen_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="a_len",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="object",
            name="b_len",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
