# Generated by Django 4.2.23 on 2025-06-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maskgen_api", "0002_alter_object_a_len_alter_object_b_len"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="a_len",
        ),
        migrations.RemoveField(
            model_name="object",
            name="b_len",
        ),
        migrations.AddField(
            model_name="object",
            name="aux",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="mask",
            name="status",
            field=models.CharField(
                choices=[
                    ("obs", "OBS"),
                    ("smf", "SMF"),
                    ("finalized", "Finalized (sent to be cut)"),
                    ("completed", "Completed (mask has been cut successfully)"),
                ],
                default="obs",
                max_length=100,
            ),
        ),
    ]
