# Generated by Django 5.2.3 on 2025-07-03 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disperser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GUIDE", "Guider"),
                            ("ALIGN", "Alignment"),
                            ("TARGET", "Target"),
                        ],
                        max_length=10,
                    ),
                ),
                ("right_ascension", models.FloatField()),
                ("declination", models.FloatField()),
                ("priority", models.IntegerField(default=0.0)),
                ("aux", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        choices=[("IMACS f/4", "Imacs F4"), ("IMACS f/2", "Imacs F2")],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                (
                    "available_dispersers",
                    models.ManyToManyField(blank=True, to="maskgen_api.disperser"),
                ),
                (
                    "available_filters",
                    models.ManyToManyField(blank=True, to="maskgen_api.filter"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mask",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("finalized", "Finalized (sent to be cut)"),
                            ("completed", "Completed (mask has been cut successfully)"),
                        ],
                        default="draft",
                        max_length=100,
                    ),
                ),
                ("features", models.JSONField()),
                ("instrument_setup", models.JSONField()),
                (
                    "instrument_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maskgen_api.instrumentconfig",
                    ),
                ),
                (
                    "excluded_obj_list",
                    models.ManyToManyField(
                        blank=True,
                        related_name="objs_not_on_mask",
                        to="maskgen_api.object",
                    ),
                ),
                (
                    "objects_list",
                    models.ManyToManyField(
                        blank=True, related_name="objs_on_mask", to="maskgen_api.object"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "objects_list",
                    models.ManyToManyField(blank=True, to="maskgen_api.object"),
                ),
            ],
            options={
                "unique_together": {("name", "user_id")},
            },
        ),
    ]
