# Generated by Django 5.2.3 on 2025-06-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maskgen_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objectlist",
            unique_together={("name", "user_id")},
        ),
    ]
