# Generated by Django 5.2.3 on 2025-07-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maskgen_api", "0002_alter_objectlist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="mask",
            name="excluded_obj_list",
            field=models.ManyToManyField(blank=True, to="maskgen_api.object"),
        ),
        migrations.AlterField(
            model_name="mask",
            name="instrument_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="objs_not_on_mask",
                to="maskgen_api.instrumentconfig",
            ),
        ),
        migrations.AlterField(
            model_name="mask",
            name="objects_list",
            field=models.ManyToManyField(
                blank=True, related_name="objs_on_mask", to="maskgen_api.object"
            ),
        ),
    ]
