# Generated by Django 5.2.3 on 2025-06-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "maskgen_api",
            "0003_remove_object_a_len_remove_object_b_len_object_aux_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "objects_list",
                    models.ManyToManyField(blank=True, to="maskgen_api.object"),
                ),
            ],
        ),
    ]
